In [1]:
# Importing necessary packages
import pandas as pd
import json

# Data Pre-processing

In [2]:
# Reading supplier data from JSON file and loading it line-by-line as it is in the form of 'list of dictionaries'
with open('supplier_car.json', 'r') as handle:
    json_data = [json.loads(line) for line in handle]

In [3]:
# Creating Pandas DataFrame to try different data operations on it, and displaying the data sample with .head() method
data_df = pd.DataFrame(json_data)
data_df.head()

,ID,MakeText,TypeName,TypeNameFull,ModelText,ModelTypeText,Attribute Names,Attribute Values,entity_id
0,976.0,MERCEDES-BENZ,McLaren,MERCEDES-BENZ SLR McLaren,SLR,SLR McLaren,Seats,2,0001fda6-192b-46a8-bc08-0e833f904eed
1,1059.0,MERCEDES-BENZ,ML 350 Inspiration,MERCEDES-BENZ ML 350 Inspiration,ML 350,ML 350 Inspiration,Hp,235,00107c2d-0071-4475-88f0-810133638b7e
2,524.0,AUDI,S6 Avant quattro 4.2,AUDI S6 Avant quattro 4.2,S6,S6 Avant quattro 4.2,FuelTypeText,Benzin,00126794-a8ef-48fe-93d6-43cfc69fbfb6
3,608.0,SAAB,9-3 2.0i-16 TS Aero,SAAB 9-3 2.0i-16 TS Aero,9-3,9-3 2.0i-16 TS Aero,Ccm,1985,00182529-1bf7-4f93-89fa-2e8e634b2c9d
4,726.0,PORSCHE,911 Turbo Cabrio,PORSCHE 911 Turbo Cabrio,911,911 Turbo Cabrio,BodyColorText,schwarz mÃ©t.,002d30c2-43f6-4905-868f-160dbc445c56

# Data Analysis

In [4]:
# To see how the data is inside the DataFrame, applying 'groupby' technique on ID (column) with
# 'unique ID', and counting the number of entries in each group i.e. about 19 in total, for each group
data_df_gb = data_df.groupby('ID')
data_df_gb.count()

,MakeText,TypeName,TypeNameFull,ModelText,ModelTypeText,Attribute Names,Attribute Values,entity_id
ID,,,,,,,,
1.0,19,19,19,19,19,19,19,19
10.0,19,19,19,0,19,19,19,19
100.0,19,19,19,19,19,19,19,19
1000.0,19,19,19,19,19,19,19,19
1001.0,19,19,19,19,19,19,19,19
...,...,...,...,...,...,...,...,...
995.0,19,19,19,19,19,19,19,19
996.0,19,19,19,19,19,19,19,19
997.0,19,19,19,19,19,19,19,19
998.0,19,19,19,19,19,19,19,19
999.0,19,19,19,19,19,19,19,19

In [5]:
# Getting a sample group to visualize particular attributes in the data
data_df_gb.get_group('4.0')

,ID,MakeText,TypeName,TypeNameFull,ModelText,ModelTypeText,Attribute Names,Attribute Values,entity_id
404,4.0,CHEVROLET,Corvette Z06,CHEVROLET Corvette Z06,CORVETTE,Corvette Z06,ConsumptionTotalText,12.7 l/100km,49daf586-563a-42e4-ba21-bef258b0a8aa
779,4.0,CHEVROLET,Corvette Z06,CHEVROLET Corvette Z06,CORVETTE,Corvette Z06,ConsumptionRatingText,G,970db28c-bc71-4c85-a590-03495346528f
1227,4.0,CHEVROLET,Corvette Z06,CHEVROLET Corvette Z06,CORVETTE,Corvette Z06,DriveTypeText,Hinterradantrieb,ec1782f9-15a7-451f-9ef6-d4056f2970ff
1838,4.0,CHEVROLET,Corvette Z06,CHEVROLET Corvette Z06,CORVETTE,Corvette Z06,BodyColorText,anthrazit,5aee1439-af59-4aed-9a6f-7e4376cde087
4319,4.0,CHEVROLET,Corvette Z06,CHEVROLET Corvette Z06,CORVETTE,Corvette Z06,Ccm,6162,2e4fe990-aeba-47d1-8443-e77564fbfb78
5857,4.0,CHEVROLET,Corvette Z06,CHEVROLET Corvette Z06,CORVETTE,Corvette Z06,Seats,2,48aca003-183b-4f95-85a2-4401b63888db
7240,4.0,CHEVROLET,Corvette Z06,CHEVROLET Corvette Z06,CORVETTE,Corvette Z06,FirstRegMonth,6,4d0dfda8-05c5-4a75-b4ad-af9c98635607
8312,4.0,CHEVROLET,Corvette Z06,CHEVROLET Corvette Z06,CORVETTE,Corvette Z06,Doors,2,12328723-a7df-490c-b43e-ea41092179fc
8628,4.0,CHEVROLET,Corvette Z06,CHEVROLET Corvette Z06,CORVETTE,Corvette Z06,InteriorColorText,schwarz,4f8c4a27-6039-4a08-b12e-f794e0d03307
12226,4.0,CHEVROLET,Corvette Z06,CHEVROLET Corvette Z06,CORVETTE,Corvette Z06,Hp,660,f7e95c57-c561-4792-9744-62f1058410bc
13033,4.0,CHEVROLET,Corvette Z06,CHEVROLET Corvette Z06,CORVETTE,Corvette Z06,Co2EmissionText,291 g/km,8a558f62-5516-47c1-942e-32d055c40a12
13283,4.0,CHEVROLET,Corvette Z06,CHEVROLET Corvette Z06,CORVETTE,Corvette Z06,TransmissionTypeText,Schaltgetriebe manuell,b7b9fb6f-80ca-4561-8455-851fe40b876a
15136,4.0,CHEVROLET,Corvette Z06,CHEVROLET Corvette Z06,CORVETTE,Corvette Z06,BodyTypeText,CoupÃ©,17d92bfa-d104-4d84-9e17-27dc28eadc5b
15604,4.0,CHEVROLET,Corvette Z06,CHEVROLET Corvette Z06,CORVETTE,Corvette Z06,Properties,"""Ab MFK"", ""Direkt-/Parallelimport""",6d1665f8-97f1-414c-9d06-a5f37b3deb1b
15653,4.0,CHEVROLET,Corvette Z06,CHEVROLET Corvette Z06,CORVETTE,Corvette Z06,Km,200,7541f429-29cd-4ebe-a4fa-0aca151b973d
17271,4.0,CHEVROLET,Corvette Z06,CHEVROLET Corvette Z06,CORVETTE,Corvette Z06,ConditionTypeText,Occasion,a4f2849c-da99-473e-b085-1257cb1d71b3
17576,4.0,CHEVROLET,Corvette Z06,CHEVROLET Corvette Z06,CORVETTE,Corvette Z06,FuelTypeText,Benzin,ddd7ffa1-101f-4f56-9c9c-80222826451b
18731,4.0,CHEVROLET,Corvette Z06,CHEVROLET Corvette Z06,CORVETTE,Corvette Z06,City,Zuzwil,b0bfc392-c28b-4fcf-bb69-bbe1d5066f9e
20714,4.0,CHEVROLET,Corvette Z06,CHEVROLET Corvette Z06,CORVETTE,Corvette Z06,FirstRegYear,2015,1e259c0f-5feb-4948-b349-93d14a3cbdf9

# Data Integration

In [6]:
# To integrate all the attributes with each 'object ID', started by getting all these attributes in the form of lists i.e.
# 19 headings, added these lists with the particular attribute-name to the DataFrame and then dropped the duplicat headings
# with the same ID
a = 0
att_dict = {}
output_data = data_df.copy()

# Applying a loop on all the groups and taking two columns of interest from it i.e. 'Att-Names' and 'Att-Values'
for group in data_df_gb:
    dt = group[1][['Attribute Names','Attribute Values']]
    
    # On the first group, taking names of attributes and saving them in a list
    # Initializing a dictionary of attributes to store attributes in each iteration for particular 'Att-names'
    if a == 0:
        a+=1
        att_names = list(group[1]['Attribute Names'])
        for name in att_names:
            att_dict[name] = []
    
    # In each group, I tried to find out all the attribute names, took particular data to the specific and relevant attribute,
    # and stored in the attributes dictionary. If any particular attribute was not found in the group, I added 'null' to that
    # dictionary
    for att in att_names:
        try:
            att_dict[att].append(dt.loc[dt['Attribute Names'] == att, 'Attribute Values'].iloc[0])
        except:
            att_dict[att].append('')

# Now at this stage, I have all the attributes for all the object-id's in a dictonarry, and I am ready to add them to DataFrame,
# so I get can integrated data for each object_id in the dataset

In [7]:
# Save the output data as a copy of the input data for now
output_data = data_df.copy()

# Delete the columns: Att-Names and Att-Values, as we are going to add them as a column for each attribute
del(output_data['Attribute Names'])
del(output_data['Attribute Values'])

# Drop duplicate data with ID, as the changing data in each duplicate entry were attributes while we are adding them as seperate
# columns for each ID
output_data = output_data.drop_duplicates(subset='ID')

# Add all the attributes columns to the ouput dataset
for name in att_names:
    output_data[name] = att_dict[name]

# Show the data-head to see the sample
output_data.head()

,ID,MakeText,TypeName,TypeNameFull,ModelText,ModelTypeText,entity_id,Km,TransmissionTypeText,ConditionTypeText,...,Properties,BodyColorText,FirstRegMonth,Hp,ConsumptionTotalText,FuelTypeText,Seats,Ccm,ConsumptionRatingText,Co2EmissionText
0,976.0,MERCEDES-BENZ,McLaren,MERCEDES-BENZ SLR McLaren,SLR,SLR McLaren,0001fda6-192b-46a8-bc08-0e833f904eed,31900,Automat,Occasion,...,"""Ab MFK""",anthrazit,1,224,11.5 l/100km,Benzin,5,3199,null,275 g/km
1,1059.0,MERCEDES-BENZ,ML 350 Inspiration,MERCEDES-BENZ ML 350 Inspiration,ML 350,ML 350 Inspiration,00107c2d-0071-4475-88f0-810133638b7e,48000,Schaltgetriebe,Oldtimer,...,"""Ab MFK""",anthrazit mÃ©t.,4,350,null,Benzin,4,3929,null,null
2,524.0,AUDI,S6 Avant quattro 4.2,AUDI S6 Avant quattro 4.2,S6,S6 Avant quattro 4.2,00126794-a8ef-48fe-93d6-43cfc69fbfb6,42600,Automatisiertes Schaltgetriebe,Occasion,...,"""Ab MFK""",blau mÃ©t.,2,400,19.3 l/100km,Benzin,2,3586,G,440 g/km
3,608.0,SAAB,9-3 2.0i-16 TS Aero,SAAB 9-3 2.0i-16 TS Aero,9-3,9-3 2.0i-16 TS Aero,00182529-1bf7-4f93-89fa-2e8e634b2c9d,23900,Automatik-Getriebe,Occasion,...,"""Ab MFK""",silber mÃ©t.,4,450,null,Benzin,0,4691,null,null
4,726.0,PORSCHE,911 Turbo Cabrio,PORSCHE 911 Turbo Cabrio,911,911 Turbo Cabrio,002d30c2-43f6-4905-868f-160dbc445c56,97100,Schaltgetriebe,Occasion,...,"""Ab MFK""",silber mÃ©t.,3,170,null,Benzin,4,1977,null,null

# Data Normalization

In [8]:
# Data Normalization:
# Normalization is done on two columns as an example. The target columns are 'TransmissionTypeText' and 'FuelTypeText'.
# For 'TransmissionTypeText', I have normalized automatic to 1 and manual to 0 respectively; for 'FuelTypeText', I have
# normalized Benzin to 1 and Diesel to 0 respectively

norm_data = output_data.copy()
norm_data.loc[norm_data['TransmissionTypeText'].isin(['Automat','Automatisiertes Schaltgetriebe','Automatik-Getriebe','Automat sequentiell']) , 'TransmissionTypeText'] = 1
norm_data.loc[norm_data['TransmissionTypeText'].isin(['Schaltgetriebe','Schaltgetriebe manuell']) , 'TransmissionTypeText'] = 0

norm_data.loc[norm_data['FuelTypeText'].isin(['Benzin']) , 'FuelTypeText'] = 1
norm_data.loc[norm_data['FuelTypeText'].isin(['Diesel']) , 'FuelTypeText'] = 0

# Showing the data sample of normalized data
norm_data.head()

,ID,MakeText,TypeName,TypeNameFull,ModelText,ModelTypeText,entity_id,Km,TransmissionTypeText,ConditionTypeText,...,Properties,BodyColorText,FirstRegMonth,Hp,ConsumptionTotalText,FuelTypeText,Seats,Ccm,ConsumptionRatingText,Co2EmissionText
0,976.0,MERCEDES-BENZ,McLaren,MERCEDES-BENZ SLR McLaren,SLR,SLR McLaren,0001fda6-192b-46a8-bc08-0e833f904eed,31900,1,Occasion,...,"""Ab MFK""",anthrazit,1,224,11.5 l/100km,1,5,3199,null,275 g/km
1,1059.0,MERCEDES-BENZ,ML 350 Inspiration,MERCEDES-BENZ ML 350 Inspiration,ML 350,ML 350 Inspiration,00107c2d-0071-4475-88f0-810133638b7e,48000,0,Oldtimer,...,"""Ab MFK""",anthrazit mÃ©t.,4,350,null,1,4,3929,null,null
2,524.0,AUDI,S6 Avant quattro 4.2,AUDI S6 Avant quattro 4.2,S6,S6 Avant quattro 4.2,00126794-a8ef-48fe-93d6-43cfc69fbfb6,42600,1,Occasion,...,"""Ab MFK""",blau mÃ©t.,2,400,19.3 l/100km,1,2,3586,G,440 g/km
3,608.0,SAAB,9-3 2.0i-16 TS Aero,SAAB 9-3 2.0i-16 TS Aero,9-3,9-3 2.0i-16 TS Aero,00182529-1bf7-4f93-89fa-2e8e634b2c9d,23900,1,Occasion,...,"""Ab MFK""",silber mÃ©t.,4,450,null,1,0,4691,null,null
4,726.0,PORSCHE,911 Turbo Cabrio,PORSCHE 911 Turbo Cabrio,911,911 Turbo Cabrio,002d30c2-43f6-4905-868f-160dbc445c56,97100,0,Occasion,...,"""Ab MFK""",silber mÃ©t.,3,170,null,1,4,1977,null,null

# Generating & Saving Data in Excel File Format

In [9]:
# Now I will create an Excel file (worksheet) with three tabs: pre-processed data, integrated data and normalized data
# Initializing the Excel writer with Pandas to store data in it
writer = pd.ExcelWriter('Target Data.xlsx', engine='xlsxwriter')

# Write each DataFrame to a different tab in the Excel worksheet
data_df.to_excel(writer, sheet_name='Pre-processing')
output_data.to_excel(writer, sheet_name='Integration')
norm_data.to_excel(writer, sheet_name='Normalisation')

# Save the Pandas Excel writer to get the desired file i.e. 'Target Data.xlsx'
writer.save()